### ISSUE TITLE
I have to select between JS and TS snippets

### ISSUE THREAD

**Issue by andys8** [mlaursen/vim-react-snippets#3]
Installed `Ultisnips`, installed this plugin, and set the command to `let g:UltiSnipsExpandTrigger="<c-j>"`.

There is a selection, that pops up, when I want to expand e.g. `fc`. The filetype is `typescript.tsx`. Do I need to configure something? Is my filetype detected as JS *and* TS at the same time? Thanks :)

![image](https://user-images.githubusercontent.com/13085980/49578460-17621480-f94a-11e8-9aa1-ce9121c9e758.png)

**Comment by mlaursen** [comment]
Hmm, what's the result of `:set filetype?`. For me, I just get `filetype=typescript`.

I'm currently using [leafgarland/typescript-vim](https://github.com/leafgarland/typescript-vim), [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript), and [mxw/vim-jsx](https://github.com/mxw/vim-jsx) for syntax highlighting and formatting which seems to allow this to work "out of the box" for me.

Side note: I should probably update my README if other people are using these snippets since it's changed a lot over time. I can add a section about how to resolve this issue as well there once we figure it out

**Comment by mlaursen** [comment]
Oh, I skipped over the

> filetype is typescript.tsx

Wonder if it'll work if you set it to `typescript` or `typescriptreact` instead since those are the two filetype snippets defined in the [UltiSnips folder](../tree/master/UltiSnips)

**Comment by blackxored** [comment]
I have this same issue, even though my `ft=typescript` (which i set manually as other plugins conflict if you've `typescriptreact`). Is still asking me to choose between a javascript snippet and a typescript one.
